### ISSUE TITLE
YouTube Music duration and progress tends to be incorrect

### ISSUE THREAD

**Issue by Geroyuni** [keifufu/WebNowPlaying#29] opened 2024-01-14 01:35 UTC
Hello there, I'm looking into an issue I'm observing with the duration of songs played by YouTube Music. I have observed a few things:
- When seeking close to the end of a track, the duration outputed by WebNowPlaying will become higher than the actual duration of the song. I have most commonly seen this to be a full minute up from the actual amount
- When YouTube Music goes to the next song but I'm in a different tab, two things are observed:
    - The duration will be the total buffered part of the song rather than the duration. Suppose a song is 3:09, but YouTube Music has buffered 30 seconds of it; In that case the duration will be 0:30, and it will keep increasing as the buffer increases, until the whole song has been buffered
     - The progress (rather than duration) will at various times throughout the song be 0 for less than a second

Some other details:
- I observed this when using YouTube Music specifically, and playing through any album or playlist. I didn't observe this on regular YouTube
- I tested Firefox (121.0.1) and Chrome (120.0.6099.217), and both of them display this issue
- The extension version is 3.0.1 for both browsers
- I tested both Rainmeter and OBS. Both display equally incorrect duration and progress

**Comment by keifufu** [comment] 2024-01-14 01:53
This is odd, the implementation for YouTube and YouTube Music are the same for both position and duration. I am not able to replicate this yet. Did this only start happening recently? v3 was released about two weeks ago.

**Comment by Geroyuni** [comment] 2024-01-14 04:57
I only started using WebNowPlaying around the time v3 was released, so I don't know of the behavior of the previous version.

**Comment by Geroyuni** [comment] 2024-01-18 02:52
I noticed that Firefox provides a pretty easy way to test older versions, so I downgraded to 2.0.10 and can confirm it behaves better. I recorded a video demonstrating the difference between current version and 2.0.10

It looks like the progress resetting to 0 generally coincides with when the duration changes.

https://github.com/keifufu/WebNowPlaying/assets/6061850/721611b0-46e1-4008-86f9-2ece22056a47

**Comment by keifufu** [comment] 2024-02-05 10:41
I am still unable to replicate this. This might be some A/B testing YTM is doing in which I am not enrolled in?

**Comment by Geroyuni** [comment] 2024-02-06 06:26
Are you using a free or premium account? I'm using premium and stop observing the issue when I sign off. There are some minor visible differences between free and premium and how it does playback that I can visibly notice. The miniplayer that is enforced on free accounts is off by default on premium, videos are usually enforced on free accounts unlike premium, and most notably there's a small delay in transitions between songs on free while transitions are instant on premium, probably because it's buffering that song in advance. Maybe that buffer on advance is the issue.

**Comment by YasogaN** [comment] 2024-02-07 05:51
As a YouTube music subscriber I can confirm this issue. So I use the old PyWnp library for this, it outputs the correct duration and position if i use the methods `media_info.position` and `media_info.duration` it gives me the correct position and duration. However if I use the `media_info.position_seconds` and `media_info.duration_seconds` it gives me weird outputs which are in accurate.

**Comment by keifufu** [comment] 2024-02-07 05:53
position/duration are directly derived from position_seconds/duration_seconds..

Either way, this being a YouTube Premium issue I'm not sure how to fix this since I will not throw money at Google.

**Comment by Geroyuni** [comment] 2024-02-07 16:09
Fair. If there's something I can do to help, let me know.

**Comment by keifufu** [comment] 2024-06-18 07:39
@Geroyuni Can you please post the results of the following commands when run in the console?

`document.querySelector("ytmusic-player-bar").playerApi.getDuration()`
`document.querySelector("ytmusic-player-bar").playerApi.getDuration(false)`
`document.querySelector("ytmusic-player-bar").playerApi.getProgressState().duration`

**Comment by Geroyuni** [comment] 2024-06-18 19:17
The 3 commands all report the same duration in seconds. The output follows the same behavior reported in the top message. Duration will change to the full time of the next song when close to the end of the current song, and starts displaying the buffered amount when the next song plays. 

I wanted to see if I could also observe the reset to 0, so I made a loop with a 1ms sleep to get the duration. It seems the durations change very quickly when it starts buffering again in a small amount of time (from 149.73240266666... to 159.7169836666666... to 169.70156366666... in less than 1/10 a second) in the time where I sometimes observe the duration of webnowplaying going to 0, but I didn't see any results to 0.

**Comment by keifufu** [comment] 2024-06-18 23:48
The position is reported correctly though, yes? 

Does the duration on the bar always show or are there scenarios where it (or the bar itself) disappears? If not then I can just read the duration from there.

**Comment by Geroyuni** [comment] 2024-06-19 23:18
The position is correct. The duration shown in the site might disappear depending on how small the window is (mobile width), the bar appears to stick around. Behavior looks the same on free accounts

**Comment by keifufu** [comment] 2024-06-20 02:31
I'll likely have this fixed in the next release then.

**Closed** 2024-06-20 07:29 UTC
